apiVersion: v1   
kind: Service
metadata:
  name: nginx-nodeport-service
  labels:
    app: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 8000
    targetPort: 80
    nodePort: 30080
