apiVersion: v1
kind: Pod
metadata:
  name: centos-pod-kata
  labels:
    app: centos-pod-kata
spec:
  runtimeClassName: kataclass
  containers:
  #- image: myregistry.com/library/busybox:v1
  - image: myregistry.com/library/centos:latest
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: "4"
        memory: "256Mi"
      requests:
        cpu: "4"
        memory: "256Mi"
    command:
      - sleep
      - "3600000"
    imagePullPolicy: IfNotPresent
    name: centos
  restartPolicy: Always
  nodeName: node5
