apiVersion: v1
kind: Pod
metadata:
  name: busyboxkuryr-master-1
  labels:
    app: busyboxkuryr-master-1
  annotations:
    v1.multus-cni.io/default-network: kuryr
    k8s.v1.cni.cncf.io/networks: kuryr
spec:
  #hostNetwork: true
  automountServiceAccountToken: false
  containers:
  - image: myregistry.com/library/busybox:v1
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  nodeName: master1
