apiVersion: v1
kind: Pod
metadata:
  name: busyboxmultus4
  labels:
    app: busyboxmultus
  annotations:
    v1.multus-cni.io/default-network: kuryr
    company.v1.product.code/name: eci
    k8s.v1.cni.cncf.io/networks: docker-conf, flannel
    projectId: 27ba05b104614724b3776388e5699503
    securityGroup: f03f848f-5d37-48ba-ae34-fd2514aad364
    subnetId: 33b4c637-71ad-40b4-b2ac-993b7742eef9
spec:
  #hostNetwork: true
  nodeName: node5
  runtimeClassName: kataclass
  automountServiceAccountToken: false
  containers:
  - image: myregistry.com/library/busybox:v1
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
