apiVersion: v1   
kind: Service
metadata:
  name: nginx-service-kubeedge
  labels:
    app: nginx-service-kubeedge
spec:
  type: ClusterIP
  selector:
    app: nginx-kubeedge
  ports:
  - port: 8000
    targetPort: 80
