apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox1-deployment
  labels:
    app: busybox1-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: busybox1
  template:
    metadata:
      labels:
        app: busybox1
    spec:
      containers:
      - name: busybox1
        image: myregistry.com/library/busybox:v1
        command:
          - sleep
          - "123600"
