apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    app: busybox2
spec:
  containers:
  - image: myregistry.com/library/busybox:v1
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  nodeName: node7
